travis:
  secure:
    BINSTAR_TOKEN: T4eJGYUq7cv8y8l0g6OE1QPRVPTV2xp6/sMkPK3ReN5nkApIyroUh5XACOeSfr7xwPTk9AsxBKkh0Z6R5g8nkyUgWoAo3QWy88uJ7k6mtQg0M3j6ecdyzrqYHex20XDtWHgDm5H1Pko+VpZLPQuoaUAVi4ddG7926AJcCBwWMr2GOp1ruBIPsDZHsqServIwADcASQHbLAHhoKedbE5W0quZ9DBQcsc7xiJvV6y25t2TUhpp5hRejMtjNuFW7P2CGovY3T+HLexjz4vN+9FEU0EIIcuQZ8pSli9jbZ7AfUtnlEGzKizZ8+HeJ3suyxOJ+HX5IyiBkHbi7wvB3NvzSESqiM+wJBTsuVvUTZ/QlRlNkw26DZrpEvRVwQQrZay5xO3ZkhJKZBu9Mdsx0EhyS2/yRFVLnzvCnaNKrhM7J69BD+P61MG42kpfDUoWLv4Hutsw+OsMA8EQ3F/mxjxKQ5vovrXwSBCoihGBjkZC9mLzs5ttlcG4CHQks9T9iaFBm82NyLXGr8/4hYp6ZiHta9PCtYAI6tW136m4q5rj5PLrJj4+ixZFELNF2JPRYetTNFB21caOuEqAbdBx1NjlnFS4R94ozO7W++UShtHZjmbEJoldQSjXUzzs4fVmVInutFtHHAnL+8CHK6hLWa7HBnODXgmA3YS1jqorVRmpHog=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
