travis:
  secure:
    BINSTAR_TOKEN: qedL3dH1PUz9ncDgZv+ig4GekfQ/88HSnAzsc+EqO7pQir13lRfByqfqf0GBPDD7x1rHKDDbP7Ehds+eCZ1SjV8yJ7uTiX5KcX08d237vTtxACVqJ/Yx8OuyUEGmoUnJRQqt479mDvGXCrkO+POK+wTPS+9BY24BHWZD+K1+nO98C5E/xOP9PfUYq24fABVha3cYHHjsEXtyoJfF5op7JhDjS+K/Q+P+3QugW53sk5xEI7Fm+MWyn6RjQ49zR2kIa2BGbgQY7CiEhaezeJ/hlsxLTHH+GmNBx3NAIymjXrSJ6YWVdwGqnrU62W3JC7JCyRQztRZUNe7Z3Qy4MJALssQp805iPg364XqmveUheyEW4mCBx7TUmqoDeMwrGKo0VngwXf/Wy69U+C0wXffm/pS8XHGtHPI22vlR8mxdyy0ZJ4iNWO0Fhn97V23GPnaXMq32cPL6HR2anQOZ/X+WNpToHEHNRBaQCXXp0KeehxDXJ3Q/OsrHj4gnrE55LcrpnF0J+gneqTNOhoDyOcCUTEL5peSR0j8av7fZ099cbAALemuGcLI7tN6QFCry70j2zWJQfj4RhdWiagAUlCgWWOm87VgP3qYfXlQ0CkABkBUQnJIldX5Fg4NeulM6KfaRMIHc/FyaV5O2bVRH6s7opmEtFiaJDSpuGpUFcCb0wys=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
