travis:
  secure:
    BINSTAR_TOKEN: h7VTcqN5k6nMc5k+baeKvbsG7vhsIfGiYH/d9y8HgFO4EsgFiteg1UDZYxZ1kE6sYfy9al+CU+Nk9AdLVEyJcuprJtwSC3cNgk45aYLNAl7CTtak//jv6Yx2RmstbDULFRzmTvKaylc5/v6h2Qr2CQHTA1WcLHvJ/t1H3Qyuxs0K8sT+Wery0f6fKieTfxV6IQXgZNSgYeTKJb3P6oqTduojmkme3xUOODPGva6CwD7COy+tM8PN37ko33oFfwRPeS0Np9TPeyU9LUZv4nAtjHuKq+C6kBj/iegBBjE1zTq2RYjl19WEMjFP8CWTNiCL2X4UHOqiBqDtUaMywbArPx55XSqz2KHGpW6KLzrAK0XjIpA3/p9xRf1vRwkMsJd818mWqDc0ZxperHzSwcEi8y8mv8HP7KQbAjCkfS6Ky4wTw1NbTEUm1mLGqZw7p/aVDvcK65+4yTAgdnhNeNogOgLXio0vMYMfb7RBCt6NW2YmPmehlHAsU9hpXtI6t9gpM2x42Xvvd6C217Rs65bD3JgyqzJIh8Cqc3tJHyq1q9FL6xwAX8E7u7bso1BYZN44shBSio3ItHvJIcBFJFT5pjVm2D/b3J3Xjf2/3IIl2x5ZK3CXH0H5oRndx8IH2JBITQN8tt3H6+GmmpB1fGlEI2EmgqnTFA1IkOvTckvMMZU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
