appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: R67akbqqcykLVmjLzwgJJ9AtryOFNPmiCuRR9067JIcP8383+iJQ6rMHP6fWIYYSGmcNfDEdElrGK3Z3jPJFFgl+oOZg8a1ilyE8tBd9Apc0LEEHjdUyhoN7ZcjJ+VRtvuTQMb9FE7meMUJeQcfAtN+RpSGeuOJ+nMQ32qU/d+HY3neP2B+IltXop8KJic9TVUWgke0AFtAv/CYyK/UHEujtVnhTZPmFGnNzv7jPHvT9bE8agVodmbTHxcGmu/dsxXOzGjyQ0alg99E4lP3xFIeKOTPpZQDohFbdaTcbI88eBd59I5koycxTn8sKYFeIHMJh6hBC+7ZPkrK6efgoJxUrQezEXy7ahPUiz5nvfWY4m4r4F182E4WY2UcT438n7wdaGMm/6GOIxwBNK8+0Uho4TNnthIJ2AHAg6g+aL3P2/0H6+TrHpVTxEHoRFm8PDIjuQaUqGNNSuUihhRVzGXJVzgezJbNMwlVEAI/7h8jzsuNRe8JQnjwoCC/lrH9mmP01sV+VwTLu0wguxtYmyVjY1A32qXxW6wawIKPSjbIj3QvlUeb6i+BG55jgl4uyz3NePN8kgS1d0q5t0wXAY7u32KfsfbjGaIgH/f4ba8j00zxyKDUTAnLD6xrmz51uvP23ZsMEeH2I6EZttUVj5sOE6qVtcB23vzDCaX53rSM=
